title: after.design after.thoughts
email: rafal+blog@malinowski.be
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site

permalink: "/:year/:month/:day/:title.html"

# Build settings
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
sass:
    style: compressed
exclude:
    - node_modules/
    - package.json
    - CNAME
